name: update-live-m3u

on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
    
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: install dependencies
        run: pip install selenium requests futures eventlet

      - name: update live m3u files
        run: python ${{ github.workspace }}/src/live.py
      
      - name: update cctv sample m3u files
        run: python ${{ github.workspace }}/src/cctv.py

      - name: force sync gitee
        run: |
          curl 'https://gitee.com/aaron2333/auto-iptv/force_sync_project' \
          --data-raw 'authenticity_token=7HgAMMsF0E%2F%2FNYoTtwePoL4aoVbqvI3cvK1EX7vVqwYCJi6BekMz8%2Bxpkdtt18fnkS4OM6CFQuODHAmrrO2zSQ%3D%3D'
        
      - name: submit
        run: |
          git config --local user.email "byang628@alumni.usc.edu"
          git config --local user.name "AaronYang"
          git add .
          git commit *.m3u -m "update m3u links"
          git push -f
