name: update-live-m3u

on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
    
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: install dependencies
        run: pip install selenium requests futures eventlet

      - name: update live m3u files
        run: python ${{ github.workspace }}/src/live.py
      
      - name: update cctv sample m3u files
        run: python ${{ github.workspace }}/src/cctv.py

      - name: force sync gitee
        run: |
          curl 'https://gitee.com/aaron2333/auto-iptv/force_sync_project' \
          -H 'Cookie: user_locale=zh-CN; oschina_new_user=false; sensorsdata2015jssdkchannel=%7B%22prop%22%3A%7B%22_sa_channel_landing_url%22%3A%22%22%7D%7D; remote_way=http; slide_id=10; BEC=1f1759df3ccd099821dcf0da6feb0357; Hm_lvt_24f17767262929947cc3631f99bfd274=1723171351,1724650411; HMACCOUNT=DF05633EED6BC5E9; user_return_to_0=%2F; tz=Asia%2FShanghai; gitee_user=true; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%221318092%22%2C%22first_id%22%3A%22191350426b9150-0e344e6157dc9a-26001e51-1204049-191350426ba6c8%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%2218d59aa70d36c7-0576e7a10b72b0c-26001951-1204049-18d59aa70d41e1%22%2C%22identities%22%3A%22eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMThkNTlhYmM5OGRhODEtMGM5N2VlOTUwOGViNmMtMjYwMDE5NTEtMTIwNDA0OS0xOGQ1OWFiYzk4ZTU1ZiIsIiRpZGVudGl0eV9sb2dpbl9pZCI6IjEzMTgwOTIifQ%3D%3D%22%2C%22history_login_id%22%3A%7B%22name%22%3A%22%24identity_login_id%22%2C%22value%22%3A%221318092%22%7D%7D; csrf_token=DVS1W8fSlLtX65N2dn8Pi60UKBg1Iwu%2B%2FV9t5o39Bi3jCpvqdpR3B0S3iL6sr0fMgiCHfX8axIHC7iASmsUeYg%3D%3D; Hm_lpvt_24f17767262929947cc3631f99bfd274=1724651051; gitee-session-n=ai9qMUExMmhEOXdUOGFTUHRPNnJpbDdHL1dvN2syL2xSMnJReUNWVGxMSm5PUWsxRmN5NG11V01MNFc4K3laaWlYSnd5cFQzTHM2WlR5TW12ZkVodE9tU2xLc0N0THhXSWYyaHJuRnZtb0lJZFFNTFZPZ0Mrb3IwQ3owUEhvNGNNUnlidFFpSnZpVFNUb1BBa0JueUF4RjZ5RTloTmMzTnorOEpyZU1LWlZmMklQUnVJSnptYytvM3pTM0ptZHN3QkdyY2ltOWd4SHgvZnc1akVpZ2NxR21HTEtGTEVob09WdmpicHJ3RitsaVlEODk0anRLMzFKRUNvaElDQ09WSlpuaGdJY0wyc1NXdlFlN3c1WndFd2RQUDlucnp4NFdTQjg1MGRBekROaE41aUVmOTRHT25jQkNNU2FuUlZtYzhNaGlFa0xkdkpFSXRPMkNpUGFWUG5XUG5VbnpkcE84RUJ1WFp0TDVRNU1lYmFzSHFzODN2VkpyS2JvNFMvVjFXK0lmdzFLTnFndi85b3JySFpuWHRrS3lXMmdiVFZCaU9RWjBTVWtlMmFobjFudm5rbWpsR0Rlcnc3bnlsYVpvSXVRRGFEcTVXQkZFa09zRUl1T1pUdVc3TzZQMkVxUXVzS2Fna0MwWnJ2TWEzK1Avc1hsazg1eE45bFpuODJkOWhBWXIrRHYrQnRPY0dsNy9jUE1MUC9DQ21wZzBaUGtJVjNJVXQrMHI5WldrcGdIVzQzRCtqWHRGbUQ3K1JRV202ZHJHWXdVWU1pQ0tkZU91Q3RuSkZYOThDVklOakdHNEJRTFBFVUVEamJXaFcvMHhQUnFVUERjZnMxbHBydzI1VC0tS0dKejM3SC9VRkdUUjd3MGs1OUIyQT09--03d3da3dfb166f63e89ada2efb859318c7b49908' \
          -H 'X-CSRF-Token: KbYYIvCLl2zs4vKaLwL9yzxUXp+0hNwePlQy59rQBEnH6DaTQc100P++6VL10rWME2Dx+v69EyEB5X8TzegcBg==' \
          --data-raw 'user_sync_code=&password_sync_code=&sync_wiki=false&prune=false&authenticity_token=7HgAMMsF0E%2F%2FNYoTtwePoL4aoVbqvI3cvK1EX7vVqwYCJi6BekMz8%2Bxpkdtt18fnkS4OM6CFQuODHAmrrO2zSQ%3D%3D'
        
      - name: submit
        run: |
          git config --local user.email "byang628@alumni.usc.edu"
          git config --local user.name "AaronYang"
          git add .
          git commit *.m3u -m "update m3u links"
          git push -f
